### ISSUE TITLE
Is the reference downloadable?

### ISSUE THREAD

**Issue by hanswzq** [imanol-arzac/Multistage-batch-reactor-model#1]
Is the reference [1] Arzac, I. I. (2022). Comparison of Dynamic Time Warping algorithms for statistical batch process monitoring. Master thesis, Katholieke Universiteit Leuven. downloadable? Want to learn more about the process, thank you very much!

**Comment by imanol-arzac** [comment]
Hey hanswzq! Unfortunately I used figures from other papers so the document cannot be shared / downloaded from the KU Leuven's intranet due to copyright infringement. Nevertheless, I suggest you have a look at the following links:
   - For the Python model and simulation code: https://github.com/imanol-arzac/Multistage-batch-reactor-model/blob/main/multistage_batch_reactor_model.ipynb
   - If you want to know more about Dynamic Time Warping, you may find many references on the following paper's appendix: https://arxiv.org/abs/2209.09660 . 
Hope this helped. Cheers,
Imanol
